name: release

on:
  push:
    branches: [master, beta]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # pulls all commits (needed for semantic release to correctly version)
          fetch-depth: "0"
          persist-credentials: false

      - uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

      - name: install dependencies
        run: yarn install --frozen-lockfile

      - name: build
        run: yarn build

      - name: test
        run: yarn test

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn semantic-release --debug
